language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
z
addons:
  sonarcloud:
    organization: sudhirtumati-github
    token:
      secure: "W1L6Lm1CUpGgyLYSGrhcYtycbzbBYDLpRiJgbDWyvnb4J75wpoU7CrJjgXhLMkVtdGPAL5GRH2PM44kFKqZaaqL+XQiIbuwTEoWL7zsDJMJd/hLBDD0VUZyePViZcp66Hi5xtNRjEArMdpRZz+jNusblQ6CqGlBrQJtCPjNkR0drpH7La5VVO2ybSK3dJztJTCBieaU3h85FytA/7sLdVEAkyySX1sXJj3tmMOEBgXoOZXddiyUJ/rlWw7i9PJQprVDCplgU09ridMrjEXLSSqR1as8SzoDCxGzVal5ylMg9JPmeMKg7sRED6ab7tRtD1qto5cT8JNjN2SFG1LTBRBMOh6j3y7OijzCzpEIOq7IFPYIqr2njP6b31FpwnDIK3C3Ck9NXuX0Q+cqP9wxPNevl2CEZZ5do81RwBndeJl7HFhcWbpyN31gBYiqmUmXZ0bfWcCgNDmCky4IQBH4RIv6GvN0vJzo9mAPsTJYX8cP0p+EM2L32i77xjhTcLmPgr0GjkTNcQZ0R5IxSV7tzky78y5klto7X/jUJNSzkg+byFjgw3N9+FOi/AkBUlxdFz9Ao5Rp8M3w8QgFejlN7B3NR7WvyUkdbdhZOuqs/l00bPni+ARfRAseSJk0pE+6eNpNffuuaPjYfpPWJJMXWmjL3l2W9Ju5t1qB4CYElBAY="

script:
   - mvn org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar